const _kindNames = <String, String>{
  'txt': 'Plain text document',
  'text': 'Plain text document',
  'log': 'Log file',
  'md': 'Markdown document',
  'markdown': 'Markdown document',
  'rst': 'reStructuredText document',
  'rtf': 'Rich text document',
  'pdf': 'PDF document',
  'doc': 'Word document',
  'docx': 'Word document',
  'odt': 'OpenDocument text',
  'pages': 'Pages document',
  'tex': 'LaTeX document',
  'epub': 'EPUB book',
  'mobi': 'Kindle book',

  'xls': 'Excel spreadsheet',
  'xlsx': 'Excel spreadsheet',
  'ods': 'OpenDocument spreadsheet',
  'numbers': 'Numbers spreadsheet',
  'csv': 'CSV spreadsheet',
  'tsv': 'TSV spreadsheet',

  'ppt': 'PowerPoint presentation',
  'pptx': 'PowerPoint presentation',
  'odp': 'OpenDocument presentation',
  'key': 'Keynote presentation',

  'png': 'PNG image',
  'jpg': 'JPEG image',
  'jpeg': 'JPEG image',
  'gif': 'GIF image',
  'bmp': 'Bitmap image',
  'tif': 'TIFF image',
  'tiff': 'TIFF image',
  'webp': 'WebP image',
  'heic': 'HEIC image',
  'heif': 'HEIF image',
  'svg': 'SVG image',
  'ico': 'Icon image',
  'avif': 'AVIF image',
  'raw': 'Raw image',
  'cr2': 'Canon raw image',
  'nef': 'Nikon raw image',
  'arw': 'Sony raw image',
  'dng': 'Digital negative image',
  'psd': 'Photoshop document',
  'ai': 'Illustrator document',
  'xcf': 'GIMP image',

  'mp4': 'MPEG-4 video',
  'm4v': 'MPEG-4 video',
  'mov': 'QuickTime video',
  'avi': 'AVI video',
  'mkv': 'Matroska video',
  'webm': 'WebM video',
  'flv': 'Flash video',
  'wmv': 'Windows Media video',
  'mpg': 'MPEG video',
  'mpeg': 'MPEG video',
  '3gp': '3GP video',

  'wav': 'WAV audio',
  'flac': 'FLAC audio',
  'aac': 'AAC audio',
  'ogg': 'Ogg audio',
  'opus': 'Opus audio',
  'm4a': 'MPEG-4 audio',
  'wma': 'Windows Media audio',
  'aiff': 'AIFF audio',
  'midi': 'MIDI audio',

  'zip': 'ZIP archive',
  'tar': 'Tar archive',
  'gz': 'Gzip archive',
  'tgz': 'Gzip archive',
  'bz2': 'Bzip2 archive',
  'xz': 'XZ archive',
  'zst': 'Zstandard archive',
  '7z': '7-Zip archive',
  'rar': 'RAR archive',
  'lz': 'Lzip archive',
  'lzma': 'LZMA archive',
  'cab': 'Cabinet archive',
  'iso': 'Disc image',
  'dmg': 'Disk image',

  'deb': 'Debian package',
  'rpm': 'RPM package',
  'apk': 'Android package',
  'msi': 'Windows installer',
  'appimage': 'AppImage application',
  'exe': 'Windows application',
  'app': 'Application',
  'jar': 'Java archive',

  'dart': 'Dart source',
  'c': 'C source',
  'h': 'C header',
  'cpp': 'C++ source',
  'cxx': 'C++ source',
  'hpp': 'C++ header',
  'cs': 'C# source',
  'java': 'Java source',
  'kt': 'Kotlin source',
  'kts': 'Kotlin script',
  'swift': 'Swift source',
  'go': 'Go source',
  'rs': 'Rust source',
  'py': 'Python source',
  'rb': 'Ruby source',
  'php': 'PHP source',
  'pl': 'Perl source',
  'lua': 'Lua source',
  'r': 'R source',
  'js': 'JavaScript source',
  'mjs': 'JavaScript source',
  'ts': 'TypeScript source',
  'tsx': 'TypeScript source',
  'jsx': 'JavaScript source',
  'vue': 'Vue component',
  'svelte': 'Svelte component',
  'sh': 'Shell script',
  'bash': 'Shell script',
  'zsh': 'Shell script',
  'fish': 'Shell script',
  'ps1': 'PowerShell script',
  'bat': 'Batch script',
  'cmd': 'Batch script',
  'sql': 'SQL script',
  'asm': 'Assembly source',
  's': 'Assembly source',
  'scala': 'Scala source',
  'clj': 'Clojure source',
  'ex': 'Elixir source',
  'exs': 'Elixir script',
  'erl': 'Erlang source',
  'hs': 'Haskell source',
  'ml': 'OCaml source',
  'jl': 'Julia source',
  'zig': 'Zig source',
  'nim': 'Nim source',

  'html': 'HTML document',
  'htm': 'HTML document',
  'css': 'CSS stylesheet',
  'scss': 'Sass stylesheet',
  'sass': 'Sass stylesheet',
  'less': 'Less stylesheet',

  'json': 'JSON document',
  'jsonc': 'JSON document',
  'yaml': 'YAML document',
  'yml': 'YAML document',
  'toml': 'TOML document',
  'ini': 'Configuration file',
  'cfg': 'Configuration file',
  'conf': 'Configuration file',
  'env': 'Environment file',
  'xml': 'XML document',
  'plist': 'Property list',
  'properties': 'Properties file',
  'lock': 'Lock file',

  'ttf': 'TrueType font',
  'otf': 'OpenType font',
  'woff': 'Web font',
  'woff2': 'Web font',
  'eot': 'Embedded font',

  'db': 'Database file',
  'sqlite': 'SQLite database',
  'sqlite3': 'SQLite database',

  'gitignore': 'Git ignore file',
  'gitattributes': 'Git attributes file',
  'dockerfile': 'Dockerfile',
};

const _fileNameKindNames = <String, String>{
  'dockerfile': 'Dockerfile',
  'containerfile': 'Containerfile',
  'makefile': 'Makefile',
  'rakefile': 'Rakefile',
  'gemfile': 'Gemfile',
  'podfile': 'Podfile',
  'readme': 'Readme document',
  'license': 'License document',
  'copying': 'License document',
  'authors': 'Authors document',
  'changelog': 'Changelog document',
};

String kindLabelForFile(String name, String extension) {
  final fileName = name.toLowerCase();
  final fileNameKind = _fileNameKindNames[fileName];
  if (fileNameKind != null) return fileNameKind;

  final extensionKind = _kindNames[extension];
  if (extensionKind != null) return extensionKind;
  if (extension.isEmpty) return 'File';

  return '${extension.toUpperCase()} file';
}

const _kindNamesZh = <String, String>{
  'Plain text document': '纯文本文档',
  'Log file': '日志文件',
  'Markdown document': 'Markdown 文档',
  'reStructuredText document': 'reStructuredText 文档',
  'Rich text document': '富文本文档',
  'PDF document': 'PDF 文档',
  'Word document': 'Word 文档',
  'OpenDocument text': 'OpenDocument 文本',
  'Pages document': 'Pages 文档',
  'LaTeX document': 'LaTeX 文档',
  'EPUB book': 'EPUB 电子书',
  'Kindle book': 'Kindle 电子书',
  'Excel spreadsheet': 'Excel 电子表格',
  'OpenDocument spreadsheet': 'OpenDocument 电子表格',
  'Numbers spreadsheet': 'Numbers 电子表格',
  'CSV spreadsheet': 'CSV 电子表格',
  'TSV spreadsheet': 'TSV 电子表格',
  'PowerPoint presentation': 'PowerPoint 演示文稿',
  'OpenDocument presentation': 'OpenDocument 演示文稿',
  'Keynote presentation': 'Keynote 演示文稿',
  'PNG image': 'PNG 图片',
  'JPEG image': 'JPEG 图片',
  'GIF image': 'GIF 图片',
  'Bitmap image': '位图图片',
  'TIFF image': 'TIFF 图片',
  'WebP image': 'WebP 图片',
  'HEIC image': 'HEIC 图片',
  'HEIF image': 'HEIF 图片',
  'SVG image': 'SVG 图片',
  'Icon image': '图标文件',
  'AVIF image': 'AVIF 图片',
  'Raw image': '原始图像',
  'Canon raw image': '佳能 RAW 图像',
  'Nikon raw image': '尼康 RAW 图像',
  'Sony raw image': '索尼 RAW 图像',
  'Digital negative image': 'DNG 数字底片',
  'Photoshop document': 'Photoshop 文档',
  'Illustrator document': 'Illustrator 文档',
  'GIMP image': 'GIMP 图片',
  'MPEG-4 video': 'MPEG-4 视频',
  'QuickTime video': 'QuickTime 视频',
  'AVI video': 'AVI 视频',
  'Matroska video': 'Matroska 视频',
  'WebM video': 'WebM 视频',
  'Flash video': 'Flash 视频',
  'Windows Media video': 'Windows Media 视频',
  'MPEG video': 'MPEG 视频',
  '3GP video': '3GP 视频',
  'WAV audio': 'WAV 音频',
  'FLAC audio': 'FLAC 音频',
  'AAC audio': 'AAC 音频',
  'Ogg audio': 'Ogg 音频',
  'Opus audio': 'Opus 音频',
  'MPEG-4 audio': 'MPEG-4 音频',
  'Windows Media audio': 'Windows Media 音频',
  'AIFF audio': 'AIFF 音频',
  'MIDI audio': 'MIDI 音频',
  'ZIP archive': 'ZIP 压缩包',
  'Tar archive': 'Tar 压缩包',
  'Gzip archive': 'Gzip 压缩包',
  'Bzip2 archive': 'Bzip2 压缩包',
  'XZ archive': 'XZ 压缩包',
  'Zstandard archive': 'Zstandard 压缩包',
  '7-Zip archive': '7-Zip 压缩包',
  'RAR archive': 'RAR 压缩包',
  'Lzip archive': 'Lzip 压缩包',
  'LZMA archive': 'LZMA 压缩包',
  'Cabinet archive': 'Cabinet 压缩包',
  'Disc image': '光盘映像',
  'Disk image': '磁盘映像',
  'Debian package': 'Debian 软件包',
  'RPM package': 'RPM 软件包',
  'Android package': 'Android 软件包',
  'Windows installer': 'Windows 安装程序',
  'AppImage application': 'AppImage 应用程序',
  'Windows application': 'Windows 应用程序',
  'Application': '应用程序',
  'Java archive': 'Java 归档',
  'Dart source': 'Dart 源码',
  'C source': 'C 源码',
  'C header': 'C 头文件',
  'C++ source': 'C++ 源码',
  'C++ header': 'C++ 头文件',
  'C# source': 'C# 源码',
  'Java source': 'Java 源码',
  'Kotlin source': 'Kotlin 源码',
  'Kotlin script': 'Kotlin 脚本',
  'Swift source': 'Swift 源码',
  'Go source': 'Go 源码',
  'Rust source': 'Rust 源码',
  'Python source': 'Python 源码',
  'Ruby source': 'Ruby 源码',
  'PHP source': 'PHP 源码',
  'Perl source': 'Perl 源码',
  'Lua source': 'Lua 源码',
  'R source': 'R 源码',
  'JavaScript source': 'JavaScript 源码',
  'TypeScript source': 'TypeScript 源码',
  'Vue component': 'Vue 组件',
  'Svelte component': 'Svelte 组件',
  'Shell script': 'Shell 脚本',
  'PowerShell script': 'PowerShell 脚本',
  'Batch script': '批处理脚本',
  'SQL script': 'SQL 脚本',
  'Assembly source': '汇编源码',
  'Scala source': 'Scala 源码',
  'Clojure source': 'Clojure 源码',
  'Elixir source': 'Elixir 源码',
  'Elixir script': 'Elixir 脚本',
  'Erlang source': 'Erlang 源码',
  'Haskell source': 'Haskell 源码',
  'OCaml source': 'OCaml 源码',
  'Julia source': 'Julia 源码',
  'Zig source': 'Zig 源码',
  'Nim source': 'Nim 源码',
  'HTML document': 'HTML 文档',
  'CSS stylesheet': 'CSS 样式表',
  'Sass stylesheet': 'Sass 样式表',
  'Less stylesheet': 'Less 样式表',
  'JSON document': 'JSON 文档',
  'YAML document': 'YAML 文档',
  'TOML document': 'TOML 文档',
  'Configuration file': '配置文件',
  'Environment file': '环境变量文件',
  'XML document': 'XML 文档',
  'Property list': '属性列表',
  'Properties file': '属性文件',
  'Lock file': '锁定文件',
  'TrueType font': 'TrueType 字体',
  'OpenType font': 'OpenType 字体',
  'Web font': 'Web 字体',
  'Embedded font': '嵌入字体',
  'Database file': '数据库文件',
  'SQLite database': 'SQLite 数据库',
  'Git ignore file': 'Git 忽略文件',
  'Git attributes file': 'Git 属性文件',
  'Dockerfile': 'Dockerfile',
  'Containerfile': 'Containerfile',
  'Makefile': 'Makefile',
  'Rakefile': 'Rakefile',
  'Gemfile': 'Gemfile',
  'Podfile': 'Podfile',
  'Readme document': '说明文档',
  'License document': '许可证文档',
  'Authors document': '作者文档',
  'Changelog document': '更新日志文档',
};

const _kindSuffixesZh = <String, String>{
  ' file': ' 文件',
  ' document': ' 文档',
  ' image': ' 图片',
  ' video': ' 视频',
  ' audio': ' 音频',
  ' archive': ' 压缩包',
  ' source': ' 源码',
  ' script': ' 脚本',
  ' package': ' 软件包',
  ' application': ' 应用程序',
  ' font': ' 字体',
  ' spreadsheet': ' 电子表格',
  ' presentation': ' 演示文稿',
  ' component': ' 组件',
  ' stylesheet': ' 样式表',
  ' database': ' 数据库',
};

String kindZhLabel(String kind) {
  if (kind == 'Folder') return '文件夹';
  if (kind == 'File') return '文件';
  final mapped = _kindNamesZh[kind];
  if (mapped != null) return mapped;

  for (final entry in _kindSuffixesZh.entries) {
    if (kind.endsWith(entry.key)) {
      return '${kind.substring(0, kind.length - entry.key.length)}${entry.value}';
    }
  }

  return kind;
}
