const _kindNames = <String, String>{
  'txt': 'Plain text document',
  'text': 'Plain text document',
  'log': 'Log file',
  'md': 'Markdown document',
  'markdown': 'Markdown document',
  'rst': 'reStructuredText document',
  'rtf': 'Rich text document',
  'pdf': 'PDF document',
  'doc': 'Word document',
  'docx': 'Word document',
  'odt': 'OpenDocument text',
  'pages': 'Pages document',
  'tex': 'LaTeX document',
  'epub': 'EPUB book',
  'mobi': 'Kindle book',

  'xls': 'Excel spreadsheet',
  'xlsx': 'Excel spreadsheet',
  'ods': 'OpenDocument spreadsheet',
  'numbers': 'Numbers spreadsheet',
  'csv': 'CSV spreadsheet',
  'tsv': 'TSV spreadsheet',

  'ppt': 'PowerPoint presentation',
  'pptx': 'PowerPoint presentation',
  'odp': 'OpenDocument presentation',
  'key': 'Keynote presentation',

  'png': 'PNG image',
  'jpg': 'JPEG image',
  'jpeg': 'JPEG image',
  'gif': 'GIF image',
  'bmp': 'Bitmap image',
  'tif': 'TIFF image',
  'tiff': 'TIFF image',
  'webp': 'WebP image',
  'heic': 'HEIC image',
  'heif': 'HEIF image',
  'svg': 'SVG image',
  'ico': 'Icon image',
  'avif': 'AVIF image',
  'raw': 'Raw image',
  'cr2': 'Canon raw image',
  'nef': 'Nikon raw image',
  'arw': 'Sony raw image',
  'dng': 'Digital negative image',
  'psd': 'Photoshop document',
  'ai': 'Illustrator document',
  'xcf': 'GIMP image',

  'mp4': 'MPEG-4 video',
  'm4v': 'MPEG-4 video',
  'mov': 'QuickTime video',
  'avi': 'AVI video',
  'mkv': 'Matroska video',
  'webm': 'WebM video',
  'flv': 'Flash video',
  'wmv': 'Windows Media video',
  'mpg': 'MPEG video',
  'mpeg': 'MPEG video',
  '3gp': '3GP video',

  'mp3': 'MP3 audio',
  'wav': 'WAV audio',
  'flac': 'FLAC audio',
  'aac': 'AAC audio',
  'ogg': 'Ogg audio',
  'opus': 'Opus audio',
  'm4a': 'MPEG-4 audio',
  'wma': 'Windows Media audio',
  'aiff': 'AIFF audio',
  'mid': 'MIDI audio',
  'midi': 'MIDI audio',

  'zip': 'ZIP archive',
  'tar': 'Tar archive',
  'gz': 'Gzip archive',
  'tgz': 'Gzip archive',
  'bz2': 'Bzip2 archive',
  'xz': 'XZ archive',
  'zst': 'Zstandard archive',
  '7z': '7-Zip archive',
  'rar': 'RAR archive',
  'lz': 'Lzip archive',
  'lzma': 'LZMA archive',
  'cab': 'Cabinet archive',
  'iso': 'Disc image',
  'dmg': 'Disk image',

  'deb': 'Debian package',
  'rpm': 'RPM package',
  'apk': 'Android package',
  'msi': 'Windows installer',
  'appimage': 'AppImage application',
  'exe': 'Windows application',
  'app': 'Application',
  'jar': 'Java archive',

  'dart': 'Dart source',
  'c': 'C source',
  'h': 'C header',
  'cpp': 'C++ source',
  'cc': 'C++ source',
  'cxx': 'C++ source',
  'hpp': 'C++ header',
  'cs': 'C# source',
  'java': 'Java source',
  'kt': 'Kotlin source',
  'kts': 'Kotlin script',
  'swift': 'Swift source',
  'go': 'Go source',
  'rs': 'Rust source',
  'py': 'Python source',
  'rb': 'Ruby source',
  'php': 'PHP source',
  'pl': 'Perl source',
  'lua': 'Lua source',
  'r': 'R source',
  'js': 'JavaScript source',
  'mjs': 'JavaScript source',
  'cjs': 'JavaScript source',
  'ts': 'TypeScript source',
  'tsx': 'TypeScript source',
  'jsx': 'JavaScript source',
  'vue': 'Vue component',
  'svelte': 'Svelte component',
  'sh': 'Shell script',
  'bash': 'Shell script',
  'zsh': 'Shell script',
  'fish': 'Shell script',
  'ps1': 'PowerShell script',
  'bat': 'Batch script',
  'cmd': 'Batch script',
  'sql': 'SQL script',
  'asm': 'Assembly source',
  's': 'Assembly source',
  'scala': 'Scala source',
  'clj': 'Clojure source',
  'ex': 'Elixir source',
  'exs': 'Elixir script',
  'erl': 'Erlang source',
  'hs': 'Haskell source',
  'ml': 'OCaml source',
  'jl': 'Julia source',
  'zig': 'Zig source',
  'nim': 'Nim source',

  'html': 'HTML document',
  'htm': 'HTML document',
  'css': 'CSS stylesheet',
  'scss': 'Sass stylesheet',
  'sass': 'Sass stylesheet',
  'less': 'Less stylesheet',

  'json': 'JSON document',
  'jsonc': 'JSON document',
  'json5': 'JSON document',
  'yaml': 'YAML document',
  'yml': 'YAML document',
  'toml': 'TOML document',
  'ini': 'Configuration file',
  'cfg': 'Configuration file',
  'conf': 'Configuration file',
  'env': 'Environment file',
  'xml': 'XML document',
  'plist': 'Property list',
  'properties': 'Properties file',
  'lock': 'Lock file',

  'ttf': 'TrueType font',
  'otf': 'OpenType font',
  'woff': 'Web font',
  'woff2': 'Web font',
  'eot': 'Embedded font',

  'db': 'Database file',
  'sqlite': 'SQLite database',
  'sqlite3': 'SQLite database',

  'gitignore': 'Git ignore file',
  'gitattributes': 'Git attributes file',
  'dockerfile': 'Dockerfile',
};

const _fileNameKindNames = <String, String>{
  'dockerfile': 'Dockerfile',
  'containerfile': 'Containerfile',
  'makefile': 'Makefile',
  'rakefile': 'Rakefile',
  'gemfile': 'Gemfile',
  'podfile': 'Podfile',
  'readme': 'Readme document',
  'license': 'License document',
  'copying': 'License document',
  'authors': 'Authors document',
  'changelog': 'Changelog document',
};

String kindLabelForFile(String name, String extension) {
  final fileName = name.toLowerCase();
  final fileNameKind = _fileNameKindNames[fileName];
  if (fileNameKind != null) return fileNameKind;

  final extensionKind = _kindNames[extension];
  if (extensionKind != null) return extensionKind;
  if (extension.isEmpty) return 'File';

  return '${extension.toUpperCase()} file';
}
