app_id: B6E1F2A4-9C3F-4D6A-9A2C-7E1D8B0F5A11
display_name: MyExplorer
executable_name: MyExplorer
artifact_name: "MyExplorer-{{build_name}}{{#has_build_number}}+{{build_number}}{{/has_build_number}}-{{platform}}{{#is_installer}}-setup{{/is_installer}}{{#ext}}.{{ext}}{{/ext}}"
publisher_name: mikolajbadyl
publisher_url: https://github.com/lixi523/Waydir
setup_icon_file: windows/runner/resources/app_icon.ico
create_desktop_icon: false
script_template: inno_setup.iss
